/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mytrip` | `/mytrip`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/generate-trip`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/review-trip`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/search-place`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/select-budget`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/select-dates`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/select-traveler`; params?: Router.UnknownInputParams; } | { pathname: `/trip-details`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mytrip` | `/mytrip`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/create-trip/generate-trip`; params?: Router.UnknownOutputParams; } | { pathname: `/create-trip/review-trip`; params?: Router.UnknownOutputParams; } | { pathname: `/create-trip/search-place`; params?: Router.UnknownOutputParams; } | { pathname: `/create-trip/select-budget`; params?: Router.UnknownOutputParams; } | { pathname: `/create-trip/select-dates`; params?: Router.UnknownOutputParams; } | { pathname: `/create-trip/select-traveler`; params?: Router.UnknownOutputParams; } | { pathname: `/trip-details`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mytrip${`?${string}` | `#${string}` | ''}` | `/mytrip${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/sign-up${`?${string}` | `#${string}` | ''}` | `/create-trip/generate-trip${`?${string}` | `#${string}` | ''}` | `/create-trip/review-trip${`?${string}` | `#${string}` | ''}` | `/create-trip/search-place${`?${string}` | `#${string}` | ''}` | `/create-trip/select-budget${`?${string}` | `#${string}` | ''}` | `/create-trip/select-dates${`?${string}` | `#${string}` | ''}` | `/create-trip/select-traveler${`?${string}` | `#${string}` | ''}` | `/trip-details${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mytrip` | `/mytrip`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/generate-trip`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/review-trip`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/search-place`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/select-budget`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/select-dates`; params?: Router.UnknownInputParams; } | { pathname: `/create-trip/select-traveler`; params?: Router.UnknownInputParams; } | { pathname: `/trip-details`; params?: Router.UnknownInputParams; };
    }
  }
}
